services:
  appApiDebug:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9000:9000
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', 'index.js']
    links:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:4.4.8
    ports:
      - '27017:27017'
    logging:
      driver: none
