version: '3.4'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5500:5500
    links: 
      - mongo
    volumes: 
      - .:/usr/src/app
  mongo:
    image: mongo:4.4.8
    ports: 
      - "27017:27017"
    logging: 
      driver: none